/*
 * This source file was generated by the Gradle 'init' task
 */
package game;
import java.io.File;
import java.util.Arrays;

import game.frame.BaseFrame;
import game.util.FontUtil;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        File dir = new File("resource");
        
        //listFilesメソッドを使用して一覧を取得する
        File[] list = dir.listFiles();
        
        System.out.println(Arrays.toString(list));
        System.out.println(new App().getGreeting());
        FontUtil font = new FontUtil();
        font.initMplus1Code();
        BaseFrame.frame_generator();
    }
}
